channels:
  - conda-forge
  - bioconda

dependencies:
  - bedtools
  - bwa
  - fastp
  - fastqc
  - pytest=9.0.2
  - r-data.table
  - r-tidyverse
  - samtools
  - scikit-learn
  - scipy
  - snakemake
  - sra-tools
